#ifndef C_CODEGEN_H
#define C_CODEGEN_H

// old-style booleans for Dart compatibility
typedef int BOOL;
#define TRUE 1
#define FALSE 0

// ----------NATIVE/SDL/RENDERWINDOW.GEN----------

typedef enum {
    SDLInitCode_Success = 0,
    SDLInitCode_InitVideo_Fail = 1,
    SDLInitCode_TTF_Init_Fail = 2,
    SDLInitCode_CreateWindow_Fail = 3,
    SDLInitCode_CreateRenderer_Fail = 4,
} SDLInitCode;

// ----------NATIVE/SDL/BEANSFONT.GEN----------

// ----------NATIVE/SDL/EVENT.GEN----------

typedef enum {
    SDLEventType_Quit = 0,
    SDLEventType_LowMemory = 1,
    SDLEventType_KeyDown = 2,
    SDLEventType_KeyUp = 3,
    SDLEventType_MouseMove = 4,
    SDLEventType_MouseDown = 5,
    SDLEventType_MouseUp = 6,
    SDLEventType_MouseScroll = 7,
    SDLEventType_FingerDown = 8,
    SDLEventType_FingerUp = 9,
    SDLEventType_FingerDrag = 10,
    SDLEventType_NotImplemented = 11,
} SDLEventType;

typedef enum {
    MouseButton_Left = 0,
    MouseButton_Middle = 1,
    MouseButton_Right = 2,
    MouseButton_Unknown = 3,
} MouseButton;

typedef enum {
    KeyCode_A = 0,
    KeyCode_B = 1,
    KeyCode_C = 2,
    KeyCode_D = 3,
    KeyCode_E = 4,
    KeyCode_F = 5,
    KeyCode_G = 6,
    KeyCode_H = 7,
    KeyCode_I = 8,
    KeyCode_J = 9,
    KeyCode_K = 10,
    KeyCode_L = 11,
    KeyCode_M = 12,
    KeyCode_N = 13,
    KeyCode_O = 14,
    KeyCode_P = 15,
    KeyCode_Q = 16,
    KeyCode_R = 17,
    KeyCode_S = 18,
    KeyCode_T = 19,
    KeyCode_U = 20,
    KeyCode_V = 21,
    KeyCode_W = 22,
    KeyCode_X = 23,
    KeyCode_Y = 24,
    KeyCode_Z = 25,
    KeyCode_One = 26,
    KeyCode_Two = 27,
    KeyCode_Three = 28,
    KeyCode_Four = 29,
    KeyCode_Five = 30,
    KeyCode_Six = 31,
    KeyCode_Seven = 32,
    KeyCode_Eight = 33,
    KeyCode_Nine = 34,
    KeyCode_Zero = 35,
    KeyCode_Exclamation = 36,
    KeyCode_Question = 37,
    KeyCode_DoubleQuote = 38,
    KeyCode_SingleQuote = 39,
    KeyCode_Pound = 40,
    KeyCode_Dollar = 41,
    KeyCode_Percent = 42,
    KeyCode_Caret = 43,
    KeyCode_Ampersand = 44,
    KeyCode_Asterisk = 45,
    KeyCode_Hyphen = 46,
    KeyCode_Underscore = 47,
    KeyCode_Equals = 48,
    KeyCode_Plus = 49,
    KeyCode_Pipe = 50,
    KeyCode_Semicolon = 51,
    KeyCode_Colon = 52,
    KeyCode_At = 53,
    KeyCode_Tilde = 54,
    KeyCode_Hash = 55,
    KeyCode_Backtick = 56,
    KeyCode_ForwardSlash = 57,
    KeyCode_BackSlash = 58,
    KeyCode_NormalBracketL = 59,
    KeyCode_NormalBracketR = 60,
    KeyCode_SquareBracketL = 61,
    KeyCode_SquareBracketR = 62,
    KeyCode_CurlyBraceL = 63,
    KeyCode_CurlyBraceR = 64,
    KeyCode_SmallerThan = 65,
    KeyCode_GreaterThan = 66,
    KeyCode_Return = 67,
    KeyCode_Escape = 68,
    KeyCode_Backspace = 69,
    KeyCode_Delete = 70,
    KeyCode_Tab = 71,
    KeyCode_Space = 72,
    KeyCode_Insert = 73,
    KeyCode_Home = 74,
    KeyCode_End = 75,
    KeyCode_PageUp = 76,
    KeyCode_PageDown = 77,
    KeyCode_ArrowRight = 78,
    KeyCode_ArrowLeft = 79,
    KeyCode_ArrowDown = 80,
    KeyCode_ArrowUp = 81,
    KeyCode_NumpadDivide = 82,
    KeyCode_NumpadMultiply = 83,
    KeyCode_NumpadSubtract = 84,
    KeyCode_NumpadAdd = 85,
    KeyCode_NumpadEquals = 86,
    KeyCode_NumpadEnter = 87,
    KeyCode_NumpadDecimalPoint = 88,
    KeyCode_NumpadOne = 89,
    KeyCode_NumpadTwo = 90,
    KeyCode_NumpadThree = 91,
    KeyCode_NumpadFour = 92,
    KeyCode_NumpadFive = 93,
    KeyCode_NumpadSix = 94,
    KeyCode_NumpadSeven = 95,
    KeyCode_NumpadEight = 96,
    KeyCode_NumpadNine = 97,
    KeyCode_NumpadZero = 98,
    KeyCode_Function_F1 = 99,
    KeyCode_Function_F2 = 100,
    KeyCode_Function_F3 = 101,
    KeyCode_Function_F4 = 102,
    KeyCode_Function_F5 = 103,
    KeyCode_Function_F6 = 104,
    KeyCode_Function_F7 = 105,
    KeyCode_Function_F8 = 106,
    KeyCode_Function_F9 = 107,
    KeyCode_Function_F10 = 108,
    KeyCode_Function_F11 = 109,
    KeyCode_Function_F12 = 110,
    KeyCode_LControl = 111,
    KeyCode_RControl = 112,
    KeyCode_LShift = 113,
    KeyCode_RShift = 114,
    KeyCode_LAlt = 115,
    KeyCode_RAlt = 116,
    KeyCode_AudioNext = 117,
    KeyCode_AudioPrev = 118,
    KeyCode_AudioStop = 119,
    KeyCode_AudioPlay = 120,
    KeyCode_Unknown = 121,
} KeyCode;

#endif // C_CODEGEN_H